### ISSUE TITLE
Deleting conversations from app

### ISSUE THREAD

**Issue by badair4400** [fetlife/android#229]
I think that we should be able to delete conversations from app and when the conversations are deleted from the website, they are still on the app. Should the app and the website be linked so that when something is deleted it's deleted from both the app and the website

**Comment by badair4400** [comment]
Yes that is want I've been noticing as well. It is like there is a syncing issue between the app and the website

**Comment by kistitan** [comment]
Hi @badair4400,

That is true,
As of now the App does think new friend / conversation but it does not remove removed one from the database.
We are working on it fix will be there in next release.
Logging out and in again using the App menu's logout menu item should however delete the database so it can be a workaround for it until the next release.

@ReluctantSub Did I understand correctly that the force logout (using the menu item from the app menu) did not remove the deleted item from the App list?

**Comment by ReluctantSub** [comment]
> @ReluctantSub Did I understand correctly that the force logout (using the menu item from the app menu) did not remove the deleted item from the App list?
@kistitan  That is correct.

**Comment by kistitan** [comment]
fixed in version 2.1

**Comment by SilverSepentes** [comment]
Deleted conversations are still not going away in the app so why was this closed when the issue hasn't been resolved

**Comment by kistitan** [comment]
Hi @SilverSepentes ,

We found and issue in the code that got fixed and we could not reproduced it anymore, so we closed the issue.
If it still happen to you indeed we are going to repoen it.
But first of all can you please confirm you are on the latest version?

If yes, please make sure that you have working internet connection when you browse our conversations.
Conversations from local cache will be removed only if during browsing the conversations information of the deletion can be retrieved from the server.

Also please note that if you start a conversation from the app you will see it in the App even if it is not visible on the website.

Thanks for your help

**Comment by SilverSepentes** [comment]
I got the app only a few months ago. Of there has been an update I don't see any info on how to do the update.

**Comment by kistitan** [comment]
Hi @SilverSepentes 

Please use the following link:
https://github.com/fetlife/android/releases/download/v2.4.0/fetlife-2.4.0.apk

**Comment by kistitan** [comment]
Please let us know if deleted conversation is still visible after refreshing the conversation list with live connection.

Thanks

**Comment by SilverSepentes** [comment]
Updated app, even signed out then went back in, deleted conversations still showing in app

**Comment by kistitan** [comment]
@SilverSepentes 

Depending on the version you have updated from, this can be a one time expected symptom.
Sign out does not clear our local data.

Please rather go to App > Settings > Profile Settings > Clear local User Data.
This should remove the Deleted conversation for sure, and hopefully with the new version it will never show up.

Please keep us updated.

Thanks again and sorry for the lots of inconveniences.
