### ISSUE TITLE
Repeated crashes

### ISSUE THREAD

**Issue by jeremymeyers** [fetlife/android#458]
Newest version on pixel 2 seems to crash a lot a lot. Immediate crash on the "about and install" page (doesn't load at all), crash when clicking on a group post update from the feed (only loads cached version add then crashes) 

Didn't give me option to send logs but happy to do so if someone tells me how.

I have cleared cache and also data and relogged in.

**Comment by FernandoMiguel** [comment]
i only had a crash with some notifications so far

**Comment by kistitan** [comment]
Hey @jeremymeyers, 

Version 2.15.5 was a quick fix for connectivity issues, and I see it indeed caused crashes with webview bases screen.
The issue should be fixed in 2.16.0 that has been released 2 minutes ago.

Please update, and sorry for the inconveniences.

**Comment by kistitan** [comment]
Please feel free to reopen the this issue if it would be still happening.

**Comment by jeremymeyers** [comment]
It's still happening on 2.16. Seems to only be happening on the "commented on a group post" feed items.

Also feed scrolling has gotten way jittery and skips around
